#! /bin/sh

# ┳━┓┓━┓┳━┓┓ ┳┏┏┓┳━┓┏━┓
# ┃━┃┗━┓┃━┛┃┃┃┃┃┃ ┃┳┛┃  
# ┇━┛━━┛┇  ┗┻┇┛ ┇┇┗┛┗━┛
#
# author: kosi <kosinwabueze@gmail.com>
# code: https://github.com/kosinw/dotfiles

# █▓▒░ workspace names
bspc monitor -d www code music comm term media ssh etc

# █▓▒░ fix various X settings
xrdb $HOME/.Xdefaults
xsetroot -cursor_name left_ptr
xset +fp /usr/share/fonts/misc
xset +fp $HOME/.local/share/fonts

# █▓▒░ foreground + background colors
query=$(xrdb -query)
background=$(echo "$query" | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(echo "$query" | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)

# █▓▒░ window border colors
bspc config normal_border_color   "#$background"
bspc config focused_border_color  "#$foreground"
bspc config presel_feedback_color "#$foreground"

# █▓▒░ window behaviors
bspc config border_width         1
bspc config window_gap           4
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true
bspc config paddingless_monocle true

# █▓▒░ rules
bspc rule -a sxiv state=floating follow=on

# █▓▒░ load urxvtd + sxhkd once
if ! pgrep -x urxvtd > /dev/null; then
    setsid urxvtd &
fi

if ! pgrep -x sxhkd > /dev/null; then
    setsid sxhkd &
fi

# █▓▒░ load feh, polybar, and dunst on every reload
$HOME/.fehbg
$HOME/.config/polybar/launch.sh
$HOME/.config/dunst/launch.sh
